/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzw_gl4study_MyNativeRender */

#ifndef _Included_com_hzw_gl4study_MyNativeRender
#define _Included_com_hzw_gl4study_MyNativeRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_OnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1OnInit
  (JNIEnv *, jobject);

/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_OnUnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1OnUnInit
  (JNIEnv *, jobject);

/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_SetParamsInt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1SetParamsInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_SetImageData
 * Signature: (III[B)V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1SetImageData
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray);

/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_OnSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1OnSurfaceCreated
  (JNIEnv *, jobject);

/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_OnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1OnSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hzw_gl4study_MyNativeRender
 * Method:    native_OnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hzw_gl4study_MyNativeRender_native_1OnDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
